[database.postgres]
dialect = "postgres"
datasource = "dbname=test sslmode=disable"
dir = "test-migrations"

[database.mysql]
dialect = "mysql"
datasource = "root@/test?parseTime=true"
dir = "test-migrations"

[database.mysql_noflag]
dialect = "mysql"
datasource = "root@/test"
dir = "test-migrations"

[database.mysql_env]
dialect = "mysql"
datasource = "${MYSQL_USER}@/$DATABASE?parseTime=true"
dir = "test-migrations"


[database.sqlite]
dialect = "sqlite3"
datasource = "test.db"
dir = "test-migrations"
table = "migrations"
